name = "Hugo Bootstrap"
license = "MIT"
licenselink = "https://github.com/Xzya/hugo-bootstrap/LICENSE.md"
description = "A hugo theme using bootstrap"
homepage = "https://github.com/Xzya/hugo-bootstrap"
tags = ["Blog", "Multilingual", "Bootstrap"]
features = ["Blog", "Responsive", "Google Analytics", "Bootstrap", "Multilingual", "i18n"]
min_version = 0.15

[author]
  name = "Mihail Cristian Dumitru"
  homepage = "https://github.com/Xzya"

[original]
  author =  "Alan Orth"
  homepage = "https://github.com/alanorth/hugo-theme-bootstrap4-blog"
  repo = "https://github.com/alanorth/hugo-theme-bootstrap4-blog"